PL/Controllers/CarroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class CarroController : Controller
    {
        // GET: Carro
        [HttpGet]
        public ActionResult GetCarro()
        {
            ML.Carro carro = new ML.Carro();
            ML.Result result = BL.Carro.GetAll();
            carro.Carros = result.Objects;
            
            return View(carro);
        }
        [HttpGet]
        public ActionResult Form(int? IdCarro)
        {
            ML.Carro carro= new ML.Carro();
            if(IdCarro != null)
            {
                ML.Result result = BL.Carro.GetById(IdCarro.Value);
                if(result.Correct) {
                    carro = (ML.Carro)result.Object;
                }

            }
            else
            {
                
            }
            return View(carro);
        }
        [HttpPost]
        public ActionResult Form(ML.Carro carro)
        {
            if(carro.IdCarro == 0)
            {
                ML.Result result = BL.Carro.Add(carro);
                if(result.Correct)
                {
                    ViewBag.Mensaje = "Se ha registrado correctamente el carro";

                }
                else
                {
                    ViewBag.Mensaje = "Error al registrar el carro";
                }
            }
            else
            {
                ML.Result result = BL.Carro.Upadate(carro);
                if(result.Correct)
                {
                    ViewBag.Mensaje = "Actualizacion exitosa de la informacion del carro";
                }
                else
                {
                    ViewBag.Mensaje = "Error al actualizar la informacion del carro";
                }
            }
            return PartialView("Modal");

        }

        [HttpPost]
        public ActionResult Eliminar(int  idCarro) {
            ML.Result result = BL.Carro.Delete(idCarro);
            if (result.Correct)
            {
                ViewBag.Mensaje = "Se elimino correctamente el carro";
            }
            else
            {
                ViewBag.Mesnaje = "Error al eliminar el carro";
            }
            return PartialView("Modal");
        }
    }

}

PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Views/Carro/Form.cshtml
@model ML.Carro
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Carro</h2>
@using (Html.BeginForm("Form", "Carro", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.HiddenFor(model => Model.IdCarro)
    <div class="container text-center">
        <div class="row row-cols-2">
            <div class="col">
                <div>
                    @Html.LabelFor(model => Model.Marca, new { @class = "" })
                    @Html.TextBoxFor(model => Model.Marca, new { @class = "form-control" })

                </div>

            </div>
            <div class="col">
                <div>
                    @Html.LabelFor(model => Model.Modelo, new { @class = "" })
                    @Html.TextBoxFor(model => Model.Modelo, new { @class = "form-control" })

                </div>
            </div>
            <div class="col">
                <div>
                    @Html.LabelFor(model => Model.NumeroSerie, new { @class = "" })
                    @Html.TextBoxFor(model => Model.NumeroSerie, new { @class = "form-control" })

                </div>
            </div>
            <div class="col">
                <div>
                    @Html.LabelFor(model => Model.Color, new { @class = "" })
                    @Html.TextBoxFor(model => Model.Color, new { @class = "form-control" })

                </div>
            </div>
            <div class="col">
                <div>
                    @Html.LabelFor(model => Model.PaisOrigen, new { @class = "" })
                    @Html.TextBoxFor(model => Model.PaisOrigen, new { @class = "form-control" })

                </div>
            </div>
            <div class="col">
                <div>
                    @Html.LabelFor(model => Model.Placa, new { @class = "" })
                    @Html.TextBoxFor(model => Model.Placa, new { @class = "form-control" })

                </div>
            </div>
           
        </div>
    </div>
    <button type="submit" class="btn btn-outline-success">Success</button>


}

PL/Views/Carro/GetCarro.cshtml
@model ML.Carro
@{
    ViewBag.Title = "GetCarro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetCarro</h2>

<a  class="btn btn-success" href="@Url.Action("Form","Carro")">Success</a>

<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">IdCarro</th>
            <th scope="col">Marca</th>
            <th scope="col">Modelo</th>
            <th scope="col">Numero de serie</th>
            <th scope="col">Color</th>
            <th scope="col">Pais de Origen</th>
            <th scope="col">Placa</th>
            <th scope="col"></th>

        </tr>
    </thead>
    <tbody>
        @foreach (ML.Carro carro in Model.Carros)
        {
            <tr>
                <th scope="row"><a class="btn btn-outline-warning" href="@Url.Action("Form", "Carro", new {IdCarro = carro.IdCarro})">Actualizar</a></th>
                <th scope="row">@carro.IdCarro</th>
                <td>@carro.Marca</td>
                <td>@carro.Modelo</td>
                <td>@carro.NumeroSerie</td>
                <td>@carro.Color</td>
                <td>@carro.PaisOrigen</td>
                <td>@carro.Marca</td>
                <td>
                    <a class="btn btn-outline-danger" href="@Url.Action("Eliminar", "Carro", new { IdCarro = carro.IdCarro})">Eliminar</a>
                </td>
            </tr>
        }

    </tbody>
    U

</table>

PL/Views/Carro/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Vale", "AddPaquete", "Paquete", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Unidad", "GetCarro", "Carro", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>